// src/lib/components/Confetti.svelte
<script lang="ts">
	let { count = 70 }: { count?: number } = $props()

	const COLORS = ['#4dff8f', '#ff4d6d', '#ffb000', '#2fe6c0', '#4dff8f', '#ffe000']

	const pieces = $derived(Array.from({ length: count }, (_, i) => ({
		left: Math.random() * 100,
		delay: Math.random() * 0.7,
		duration: 2 + Math.random() * 1.6,
		size: 7 + Math.random() * 7,
		color: COLORS[i % COLORS.length],
		round: Math.random() > 0.5
	})))
</script>

<div aria-hidden="true" class="pointer-events-none fixed inset-0 z-50 overflow-hidden">
	{#each pieces as p, i (i)}
		<span
			class="absolute top-0 animate-confetti"
			style="left:{p.left}%; width:{p.size}px; height:{p.size * (p.round ? 1 : 0.45)}px;
				background-color:{p.color}; border-radius:{p.round ? '50%' : '2px'};
				animation-delay:{p.delay}s; animation-duration:{p.duration}s;
				box-shadow: 0 0 8px {p.color}"
		></span>
	{/each}
</div>

// src/components/Confetti.tsx
import { useMemo } from 'react'

const COLORS = ['#7c5cff', '#ff5470', '#ffb02e', '#22b8e6', '#3ecf6e', '#f5d547']

/** Lightweight CSS confetti burst rendered on wins. Purely decorative. */
export function Confetti({ count = 70 }: { count?: number }) {
  const pieces = useMemo(
    () =>
      Array.from({ length: count }, (_, i) => ({
        left: Math.random() * 100,
        delay: Math.random() * 0.7,
        duration: 2 + Math.random() * 1.6,
        size: 7 + Math.random() * 7,
        color: COLORS[i % COLORS.length],
        round: Math.random() > 0.5,
      })),
    [count],
  )

  return (
    <div aria-hidden className="pointer-events-none fixed inset-0 z-50 overflow-hidden">
      {pieces.map((p, i) => (
        <span
          key={i}
          className="absolute top-0 animate-confetti"
          style={{
            left: `${p.left}%`,
            width: p.size,
            height: p.size * (p.round ? 1 : 0.45),
            backgroundColor: p.color,
            borderRadius: p.round ? '50%' : 2,
            animationDelay: `${p.delay}s`,
            animationDuration: `${p.duration}s`,
          }}
        />
      ))}
    </div>
  )
}
